browser=chrome
url=http://127.0.0.1/opencartsite/

email=standard_user@test.com
password=Test@123
api_username=Automator
api_key=WyrpHUJqXVbtNt40j3lPMxQAuFgqaJCcWqEBigoFxBBJns6sffip2xzChVjLLxvfjS56Y73JWSU45p4ZuQ7LhZcVm8BfWuaaCpRezztWwp3Xw5QPfDHHpRPpucYrL8aUvCnZR3gAuTfmIKdvLhtIHQjTboL0IkDQZjCuInj1WvvdshtAh4rNLJenue1tg6oPTuNTM3wqsFB3odnPhNScKQ8Z2LjcEy0c4xLvNhva37EiVnOYKRIRtagQAZteAO06